(import (scheme base)
        (scheme write)
        (only (srfi 1) circular-list?)
        (srfi 78))

(let ((x (list 'a 'b 'c)))
  (set-cdr! (cddr x) x)
  (check (circular-list? x) => #t)
  (newline)
  (write x)
  (newline))

(let ((x (list 'a)))
  (set-cdr! x x)
  (check (circular-list? x) => #t)
  (newline)
  (write x)
  (newline))

(let ((x (list 1)))
  (newline)
  (write (list x x))
  (newline))

(let ((x (list 1)))
  (newline)
  (write-shared (list x x))
  (newline))

(let ((x '#0=(a b c . #0#)))
  (check (circular-list? x) => #t)
  (newline)
  (write x)
  (newline))

(let ((x '#0=(a b c (d e f . #0#))))
  (check (circular-list? x) => #f)
  (newline)
  (write-shared x)
  (newline))
