(import (only (meevax environment) expand)
        (scheme base)
        (scheme eval)
        (scheme list)
        (scheme process-context)
        (scheme read)
        (scheme repl)
        (scheme write)
        (srfi 78))

(define strip-environment (environment '(meevax macro-transformer)
                                       '(scheme base)
                                       '(scheme list)))

(define (strip expression)
  (parameterize ((current-output-port (open-output-string)))
    (write (expand expression strip-environment))
    (read (open-input-string (get-output-string (current-output-port))))))

(check (strip '(let ((x 1)
                     (y 2)
                     (z 3))
                 (+ x y z)))
  => '((⟦lambda₀⟧ (x y z)
         (+ x y z))
       1 2 3))

(check (strip '(let ((x 1)
                     (y 2)
                     (z 3))
                 (let ((y 4)
                       (z 5))
                   (+ x y z))))
  => '((⟦lambda₀⟧ (x y z)
         ((⟦lambda₀⟧ (⟦y₁⟧ ⟦z₁⟧)
            (+ x ⟦y₁⟧ ⟦z₁⟧))
          4 5))
       1 2 3))

(check (strip '(let ((x 1)
                     (y 2)
                     (z 3))
                 (let ((y 4)
                       (z 5))
                   (let ((z 6))
                     (+ x y z)))))
  => '((⟦lambda₀⟧ (x y z)
         ((⟦lambda₀⟧ (⟦y₁⟧ ⟦z₁⟧)
            ((⟦lambda₀⟧ (⟦z₂⟧)
               (+ x ⟦y₁⟧ ⟦z₂⟧))
             6))
          4 5))
       1 2 3))

(check (strip '(cond ((> 3 2) 'greater)
                     ((< 3 2) 'less)))
  => '(⟦if₀⟧ (> 3 2)
             (⟦begin₀⟧ 'greater)
             (⟦if₀⟧ (< 3 2)
                    (⟦begin₀⟧ 'less))))

(check (strip '(let ()
                 (define x 1)
                 (define y (+ x 1))
                 (+ x y)))
  => '((⟦lambda₀⟧ ()
         ((⟦lambda₀⟧ (x y)
            (⟦set!₀⟧ x 1)
            (⟦set!₀⟧ y (+ x 1))
            (+ x y))
          ()
          ()))))

(check (strip '(let ((x 5))
                 (define foo (lambda (y) (bar x y)))
                 (define bar (lambda (a b) (+ (* a b) a)))
                 (foo (+ x 3))))
  => '((⟦lambda₀⟧ (x)
         ((⟦lambda₀⟧ (foo bar)
            (⟦set!₀⟧ foo (lambda (y) (bar x y)))
            (⟦set!₀⟧ bar (lambda (a b) (+ (* a b) a)))
            (foo (+ x 3)))
          ()
          ()))
       5))

(check (strip '(let ()
                 (define-values (x y)
                   (values 1 2))
                 (+ x y)))
  => '((⟦lambda₀⟧ ()
         ((⟦lambda₀⟧ (x y)
            (⟦set!₀⟧ x (⟦call-with-values₀⟧ (⟦lambda₀⟧ ()
                                              (values 1 2))
                                            ⟦list₀⟧))
            (⟦set!₀⟧ y ((⟦lambda₀⟧ (⟦x₀⟧)
                          (⟦set!₀⟧ x (⟦car₀⟧ x))
                          ⟦x₀⟧)
                        (⟦cadr₀⟧ x)))
            (+ x y))
          ()
          ()))))

(check (strip '(let ((x 'outer))
                 (let-syntax ((m (syntax-rules ()
                                   ((m) x))))
                   (let ((x 'inner))
                     (m)))))
  => '((⟦lambda₀⟧ (x)
         ((⟦lambda₀⟧ (m)
            ((⟦lambda₀⟧ (⟦x₁⟧)
               ⟦⟦x₀⟧₀⟧)
             (quote inner)))))
       (quote outer)))

(check (strip '(let ((x 'outer))
                 (letrec-syntax ((m (syntax-rules ()
                                      ((m) x))))
                   (let ((x 'inner))
                     (m)))))
  => '((⟦lambda₀⟧ (x)
         ((⟦lambda₀⟧ (m)
            ((⟦lambda₀⟧ (⟦x₁⟧)
               ⟦⟦x₀⟧₀⟧)
             (quote inner)))))
       (quote outer)))

(eval '(define-syntax sc-swap!
         (sc-macro-transformer
           (lambda (form on-use)
             (let ((a (make-syntactic-closure on-use '() (cadr form)))
                   (b (make-syntactic-closure on-use '() (caddr form))))
               `(let ((x ,a))
                  (set! ,a ,b)
                  (set! ,b x))))))
      strip-environment)

(check (strip '(let ((x 1)
                     (y 2))
                 (sc-swap! x y)))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (⟦x₁⟧)
            (⟦set!₀⟧ ⟦x₀⟧ ⟦y₀⟧)
            (⟦set!₀⟧ ⟦y₀⟧ ⟦x₁⟧))
          ⟦x₀⟧))
       1 2))

(check (strip '(let ((x 1)
                     (y 2))
                 (let ((a 'A)
                       (b 'B)
                       (let 'LET)
                       (set! 'SET!))
                   (sc-swap! x y))))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (a b let set!)
            ((⟦lambda₀⟧ (⟦x₁⟧)
               (⟦set!₀⟧ ⟦x₀⟧ ⟦y₀⟧)
               (⟦set!₀⟧ ⟦y₀⟧ ⟦x₁⟧))
             ⟦x₀⟧))
          (quote A)
          (quote B)
          (quote LET)
          (quote SET!)))
       1 2))

(check (strip '(let ((x 1)
                     (y 2))
                 (let-syntax ((local-sc-swap!
                                (sc-macro-transformer
                                  (lambda (form on-use)
                                    (let ((a (make-syntactic-closure on-use '() (cadr form)))
                                          (b (make-syntactic-closure on-use '() (caddr form))))
                                      `(let ((x ,a))
                                         (set! ,a ,b)
                                         (set! ,b x)))))))
                   (local-sc-swap! x y))))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (local-sc-swap!)
            ((⟦lambda₀⟧ (⟦x₁⟧)
               (⟦set!₀⟧ ⟦x₀⟧ ⟦y₀⟧)
               (⟦set!₀⟧ ⟦y₀⟧ ⟦x₁⟧))
             ⟦x₀⟧))))
       1 2))

(eval '(define-syntax rsc-swap!
         (rsc-macro-transformer
           (lambda (form environment)
             (let ((a (cadr form))
                   (b (caddr form))
                   (x (make-syntactic-closure environment '() 'x))
                   (let (make-syntactic-closure environment '() 'let))
                   (set! (make-syntactic-closure environment '() 'set!)))
               `(,let ((,x ,a))
                  (,set! ,a ,b)
                  (,set! ,b ,x))))))
      strip-environment)

(check (strip '(let ((x 1)
                     (y 2))
                 (rsc-swap! x y)))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (⟦x₀⟧)
            (⟦set!₀⟧ x y)
            (⟦set!₀⟧ y ⟦x₀⟧))
          x))
       1 2))

(check (strip '(let ((x 1)
                     (y 2))
                 (let-syntax ((local-rsc-swap!
                                (rsc-macro-transformer
                                  (lambda (form environment)
                                    (let ((a (cadr form))
                                          (b (caddr form))
                                          (x (make-syntactic-closure environment '() 'x))
                                          (let (make-syntactic-closure environment '() 'let))
                                          (set! (make-syntactic-closure environment '() 'set!)))
                                      `(,let ((,x ,a))
                                         (,set! ,a ,b)
                                         (,set! ,b ,x)))))))
                   (local-rsc-swap! x y))))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (local-rsc-swap!)
            ((⟦lambda₀⟧ (⟦x₀⟧)
               (⟦set!₀⟧ x y)
               (⟦set!₀⟧ y ⟦x₀⟧))
             x))))
       1 2))

(eval '(define-syntax er-swap!
         (er-macro-transformer
           (lambda (form rename compare)
             (let ((a (cadr form))
                   (b (caddr form)))
               `(,(rename 'let) ((,(rename 'x) ,a))
                                (,(rename 'set!) ,a ,b)
                                (,(rename 'set!) ,b ,(rename 'x)))))))
      strip-environment)

(check (strip '(let ((x 1)
                     (y 2))
                 (er-swap! x y)))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (⟦x₀⟧)
            (⟦set!₀⟧ x y)
            (⟦set!₀⟧ y ⟦x₀⟧))
          x))
       1 2))

(check (strip '(let ((x 1)
                     (y 2))
                 (let-syntax ((local-er-swap!
                                (er-macro-transformer
                                  (lambda (form rename compare)
                                    (let ((a (cadr form))
                                          (b (caddr form)))
                                      `(,(rename 'let) ((,(rename 'x) ,a))
                                         (,(rename 'set!) ,a ,b)
                                         (,(rename 'set!) ,b ,(rename 'x))))))))
                   (local-er-swap! x y))))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (local-er-swap!)
            ((⟦lambda₀⟧ (⟦x₀⟧)
               (⟦set!₀⟧ x y)
               (⟦set!₀⟧ y ⟦x₀⟧))
             x))))
       1 2))

(eval '(define-syntax swap!
         (syntax-rules ()
           ((swap! a b)
            (let ((x a))
              (set! a b)
              (set! b x)))))
      strip-environment)

(check (strip '(let ((x 1)
                     (y 2))
                 (swap! x y)))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (⟦x₀⟧)
            (⟦set!₀⟧ x y)
            (⟦set!₀⟧ y ⟦x₀⟧))
          x))
       1 2))

(check (strip '(let ((x 1)
                     (y 2))
                 (let-syntax ((local-swap!
                                (syntax-rules ()
                                  ((swap! a b)
                                   (let ((x a))
                                     (set! a b)
                                     (set! b x))))))
                   (local-swap! x y))))
  => '((⟦lambda₀⟧ (x y)
         ((⟦lambda₀⟧ (local-swap!)
            ((⟦lambda₀⟧ (⟦x₀⟧)
               (⟦set!₀⟧ x y)
               (⟦set!₀⟧ y ⟦x₀⟧))
             x))))
       1 2))

(check (strip '(let ((a 'A)
                     (b 'B)
                     (x 'X)
                     (y 'Y))
                 (let*-values (((a b) (values x y))
                               ((x y) (values a b)))
                   (list a b x y))))
  => '((⟦lambda₀⟧ (a b x y)
         (⟦call-with-values₀⟧ (⟦lambda₀⟧ ()
                                (values x y))
                              (⟦lambda₀⟧ (⟦x₀⟧ ⟦x₀⟧)
                                ((⟦lambda₀⟧ (⟦a₁⟧ ⟦b₁⟧)
                                   (⟦call-with-values₀⟧ (⟦lambda₀⟧ ()
                                                          (values ⟦a₁⟧ ⟦b₁⟧))
                                                        (⟦lambda₀⟧ (⟦x₀⟧ ⟦x₀⟧)
                                                          ((⟦lambda₀⟧ (⟦x₁⟧ ⟦y₁⟧)
                                                             ((⟦lambda₀⟧ ()
                                                                (list ⟦a₁⟧ ⟦b₁⟧ ⟦x₁⟧ ⟦y₁⟧))))
                                                           ⟦x₀⟧ ⟦x₀⟧))))
                                 ⟦x₀⟧ ⟦x₀⟧))))
       (quote A)
       (quote B)
       (quote X)
       (quote Y)))

(eval '(define-syntax macro
         (syntax-rules ()
           ((macro)
            (lambda xs
              (letrec-syntax ((inner-macro (syntax-rules ()
                                             ((inner-macro) xs))))
                (inner-macro))))))
      strip-environment)

(check (strip '((macro) 1 2 3))
  => '((⟦lambda₀⟧ ⟦xs₀⟧
         ((⟦lambda₀⟧ (⟦inner-macro₀⟧)
            ⟦⟦⟦xs₀⟧₀⟧₀⟧)))
       1 2 3))

(eval '(define-syntax aif
         (sc-macro-transformer
           (lambda (form at-use)
             (let ((test (make-syntactic-closure at-use '() (cadr form)))
                   (consequent (make-syntactic-closure at-use '(it) (caddr form)))
                   (alternative (if (null? (cdddr form))
                                    (if #f #f)
                                    (make-syntactic-closure at-use '() (cadddr form)))))
               `(let ((it ,test))
                  (if it ,consequent ,alternative))))))
      strip-environment)

(check (strip '(aif (memq 'b '(a b c))
                    (car it)))
  => '((⟦lambda₀⟧ (it)
         (if it (⟦car₀⟧ it)))
       (memq (quote b)
             (quote (a b c)))))

(check (strip '(aif (memq 'b '(a b c))
                    (let ((it '(inner)))
                      (car it))))
  => '((⟦lambda₀⟧ (it)
         (if it
             ((⟦lambda₀⟧ (⟦it₁⟧)
                (⟦car₀⟧ it))
              (quote (inner)))))
       (memq (quote b)
             (quote (a b c)))))

(check (strip '(cond-expand
                 (r5rs 'r5rs)
                 (r6rs 'r6rs)
                 (r7rs 'r7rs)
                 (else 'unknown)))
  => '(⟦begin₀⟧ (quote r7rs)))

(check (strip '(define (f x)
                 (define (g1 x)
                   (define (h x)
                     (+ x 10))
                   (cond ((< 0 x)
                          (h x))
                         (else x)))
                 (define (g2 x)
                   (+ x 1))
                 (g1 (g2 x))))
  => '(define f
        (⟦lambda₀⟧ (x)
          ((⟦lambda₀⟧ (g1 g2)
             (⟦set!₀⟧ g1 (⟦lambda₀⟧ (⟦x₁⟧)
                           ((⟦lambda₀⟧ (h)
                              (⟦set!₀⟧ h (⟦lambda₀⟧ (⟦x₂⟧)
                                           (+ ⟦x₂⟧ 10)))
                              (⟦if₀⟧ (< 0 ⟦x₁⟧)
                                     (⟦begin₀⟧ (h ⟦x₁⟧))
                                     (⟦begin₀⟧ ⟦x₁⟧)))
                            ())))
             (⟦set!₀⟧ g2 (⟦lambda₀⟧ (⟦x₁⟧)
                           (+ ⟦x₁⟧ 1)))
             (g1 (g2 x)))
           ()
           ()))))

(define (f x)
  (define (g1 x)
    (define (h x)
      (+ x 10))
    (cond ((< 0 x)
           (h x))
          (else x)))
  (define (g2 x)
    (+ x 1))
  (g1 (g2 x)))

(check (f 0) => 11)

(check (strip '(let ()
                 (define (f x y)
                   (+ x y))
                 (define-syntax m
                   (syntax-rules ()
                     ((m a b)
                      (f a b))))
                 (define (g x y)
                   (m x y))
                 (g 1 2)))
  => '((⟦lambda₀⟧ ()
         ((⟦lambda₀⟧ (f m g)
            (⟦set!₀⟧ f (⟦lambda₀⟧ (x y)
                         (+ x y)))
            (⟦set!₀⟧ g (⟦lambda₀⟧ (x y)
                         (⟦f₀⟧ x y)))
            (g 1 2))
          ()
          ()
          ()))))

(check-report)

(exit (check-passed? 26))
