(define-library (srfi 23)
  (import (only (meevax error) make-error)
          (only (scheme r5rs) define apply)
          (only (srfi 34) raise))
  (export error)
  (begin (define (error . xs)
           (raise (apply make-error xs)))))
