(define-library (srfi 6)
  (import (meevax port))
  (export (rename open-string open-input-string)
          (rename open-string open-output-string)
          (rename port->string get-output-string)))
