(define (error message . irritants)
  (display "error: ")
  (display message)
  (for-each (lambda (each)
              (display " ")
              (write each))
            irritants)
  (newline)
  (exit #f))
