name: Build and Test
on:
  push:
  schedule:
    - cron: 0 0 * * *
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ g++, clang++ ]
        configuration: [ Debug, Release ]
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - run: ./script/setup.sh --update --all
      - run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
      - run: cmake --build build --parallel $(nproc)
      - run: sudo cmake --install build
      - run: sudo ldconfig
      - working-directory: build
        run: make test ARGS=-j"$(nproc)"
  Package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - run: ./script/setup.sh --update --required
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - working-directory: build
        run: |
          # cmake --build . --parallel $(nproc)
          cpack --verbose
          sudo dpkg -i *.deb
