name: "CI"

on: push
# on:
#   push:
#     branches:
#       - "!*"
#     tags:
#       - "v*"

jobs:
  Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        compiler: [ g++-7, g++-9, clang++-6.0, clang++-9 ]
        configuration: [ Debug, Release ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: 1. Setup
        run: |
          sudo apt update
          sudo apt install libboost-all-dev libgmp-dev

      - name: 2. Configure
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          mkdir -p build && cd $_
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: 3. Make
        working-directory: build
        run: make

      - name: 4. Install
        working-directory: build
        run: |
          sudo make install
          sudo ldconfig

      - name: 5. Test
        working-directory: build
        run: |
          sudo apt install valgrind
          meevax -d ../basis/experimental/srfi-78.ss ../test/r4rs.ss
          make test
