name: "CI"

on: push
# on:
#   push:
#     branches:
#       - "!*"
#     tags:
#       - "v*"

jobs:
  Ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        compiler: [ g++-7, g++-9, clang++-6.0, clang++-9 ]
        configuration: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v1

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install libboost-all-dev libgmp-dev libmpfr-dev

      - name: Configure
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          mkdir -p build && cd $_
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Make
        working-directory: build
        run: make -j1

      - name: Install
        working-directory: build
        run: |
          sudo make install
          sudo ldconfig

      - name: R4RS tests
        run: ice standard/experimental/srfi-78.ss test/r4rs.ss

      - name: Chibi-Scheme basic tests
        run: ice standard/experimental/srfi-78.ss test/chibi-basic.ss
