name: Packaging
on:
  push: # Experimental
jobs:
  Packaging:
    runs-on: ${{ matrix.os }}
    env:
      DEBEMAIL: httperror@404-notfound.jp
      DEBFULLNAME: Tatsuya Yamasaki
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install build-essential cdbs devscripts dh-make fakeroot pbuilder
      - run: |
          git archive HEAD --format tar.gz \
                           --output meevax-$(cat VERSION).tar.gz \
                           --prefix meevax-$(cat VERSION)/ \
                           --verbose
      - run: tar xzvf meevax-$(cat VERSION).tar.gz
      - run: |
          cd meevax-$(cat VERSION)
          dh_make --copyright apache \
                  --createorig \
                  --library \
                  --yes
          rm debian/*.EX \
             debian/*.docs \
             debian/*.ex \
             debian/README.*
