name: Release
on:
  push:
    branches:
      - master
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - run: ./script/setup-ubuntu.sh
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --target package
      - run: gh release create v${{ env.VERSION }} build/meevax_${{ env.VERSION }}_amd64.deb --title "Version ${{ env.VERSION }}"
        env:
         GH_TOKEN: ${{ github.token }}
