name: Release
on:
  push:
    branches:
      - master
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - run: ./script/setup.sh
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --target package
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Version ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_name: meevax_${{ env.VERSION }}_amd64.deb
          asset_path: build/meevax_${{ env.VERSION }}_amd64.deb
