name: Release
on:
  push:
    # branches:
    #   - master
jobs:
  Debian:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./script/setup.sh --update --required
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --build build --target package
      - run: |
          git tag v$(cat VERSION | tr -d "\n")
          git push origin v$(cat VERSION | tr -d "\n")
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release $(cat VERSION | tr -d "\n")
          tag_name: v$(cat VERSION | tr -d "\n")
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_name: meevax_$(cat VERSION | tr -d "\n")_amd64.deb
          asset_path: build/meevax_$(cat VERSION | tr -d "\n")_amd64.deb
