name: Release
on:
  push:
    # branches:
    #   - master
jobs:
  Debian:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - run: echo v${VERSION}
      - run: ./script/setup.sh --update --required
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --build build --target package
      - run: |
          git tag v${VERSION}
          git push origin --tags
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${VERSION}
          tag_name: v${VERSION}
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_name: meevax_${VERSION}_amd64.deb
          asset_path: build/meevax_${VERSION}_amd64.deb
